import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global.css";
import StyledComponentsRegistry from "../lib/registry";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ComuFeed",
  // description: "Generated by create next app",
};

export default function RootLayout(props: React.PropsWithChildren) {
  return (
    <html>
      <body className={inter.className}>
        <StyledComponentsRegistry>{props.children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}
